service: hotel-booking-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::565393056445:role/hotel-booking-project

functions:
  CreateBooking:
    handler: functions/CreateBooking/index.handler
    events:
      - httpApi:
          path: /bookings
          method: post

  UpdateBooking:
    handler: functions/UpdateBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{bookingId}
          method: put

  GetBooking:
    handler: functions/GetBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{bookingId}
          method: get

  GetAllBookings:
    handler: functions/GetAllBookings/index.handler
    events:
      - httpApi:
          path: /bookings
          method: get

resources:
  Resources:
    BookingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookings
        AttributeDefinitions:
          - AttributeName: "bookingId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "bookingId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
